name: Create Empty Daily Note
on:
  schedule:
    - cron: "0 6 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npx nx run tools/note-utils:create-fleeting-note
        env:
          GH_KEY: ${{ secrets.GH_KEY }}
          OWNER: ${{ secrets.OWNER }}
          REPO: ${{ secrets.REPO }}
          NAME: ${{ secrets.NAME }}
          EMAIL: ${{ secrets.EMAIL }}
