name: Deploy newsletter.chiubaca.com to Cloudflare
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install
      - name: Build newsletter
        run: pnpm --filter newsletter.chiubaca.com build
      - name: Publish to Cloudflare
        run: pnpm --filter newsletter.chiubaca.com deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
