# .github/workflows/deploy.yml
name: Redeploy chiubaca.com to Cloudflare worker

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Build chiubaca.com
        run: pnpm -w run chiubaca.com:build
      - name: Publish to Cloudflare
        run: pnpm -w run chiubaca.com:deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
