name: Redeploy chiubaca.com to Cloudflare worker
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --workspaces
      - name: Build chiubaca.com
        run: npm run chiubaca.com:build
      - name: Publish to Cloudflare
        run: npm run chiubaca.com:deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
